-- DEPRECATED: parei de usar
-- local Self = {}
--
-- function Self.config()
-- 	local lens_status_ok, session_lens = pcall(require, "session-lens")
-- 	local auto_status_ok, auto_session = pcall(require, "auto-session")
--
-- 	if not lens_status_ok or not auto_status_ok then
-- 		return
-- 	end
--
-- 	auto_session.setup({
-- 		log_level = "info",
-- 		auto_session_enabled = true,
-- 		auto_save_enabled = true,
-- 		auto_restore_enabled = false,
-- 		auto_session_suppress_dirs = { "~/", "~/workspace" },
-- 		pre_save_cmds = { "NvimTreeClose" },
-- 	})
--
-- 	session_lens.setup({})
-- end
--
-- return Self

-- Keymaps
-- -- Session commands
-- S = {
-- 	name = "Sessions",
-- 	l = { "<CMD>Telescope session-lens search_session<CR>", "List" },
-- 	r = { "<CMD>RestoreSession<CR>", "Restore" },
-- 	d = { "<CMD>DeleteSession<CR>", "Delete" },
-- 	s = { "<CMD>SaveSession<CR>", "Save" },
-- },
